# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replicator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='replicator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10replicator.proto\x1a\x1cgoogle/protobuf/struct.proto\"$\n\x11PostgresDBRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cMongoDBReply\x12\x0f\n\x07message\x18\x01 \x01(\t2G\n\nReplicator\x12\x39\n\x12ReplicateInMongoDB\x12\x12.PostgresDBRequest\x1a\r.MongoDBReply\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_POSTGRESDBREQUEST = _descriptor.Descriptor(
  name='PostgresDBRequest',
  full_name='PostgresDBRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='PostgresDBRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=86,
)


_MONGODBREPLY = _descriptor.Descriptor(
  name='MongoDBReply',
  full_name='MongoDBReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='MongoDBReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['PostgresDBRequest'] = _POSTGRESDBREQUEST
DESCRIPTOR.message_types_by_name['MongoDBReply'] = _MONGODBREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PostgresDBRequest = _reflection.GeneratedProtocolMessageType('PostgresDBRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTGRESDBREQUEST,
  '__module__' : 'replicator_pb2'
  # @@protoc_insertion_point(class_scope:PostgresDBRequest)
  })
_sym_db.RegisterMessage(PostgresDBRequest)

MongoDBReply = _reflection.GeneratedProtocolMessageType('MongoDBReply', (_message.Message,), {
  'DESCRIPTOR' : _MONGODBREPLY,
  '__module__' : 'replicator_pb2'
  # @@protoc_insertion_point(class_scope:MongoDBReply)
  })
_sym_db.RegisterMessage(MongoDBReply)



_REPLICATOR = _descriptor.ServiceDescriptor(
  name='Replicator',
  full_name='Replicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=121,
  serialized_end=192,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReplicateInMongoDB',
    full_name='Replicator.ReplicateInMongoDB',
    index=0,
    containing_service=None,
    input_type=_POSTGRESDBREQUEST,
    output_type=_MONGODBREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLICATOR)

DESCRIPTOR.services_by_name['Replicator'] = _REPLICATOR

# @@protoc_insertion_point(module_scope)
