# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import replicator_pb2 as replicator__pb2


class ReplicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplicateInMongoDB = channel.unary_unary(
                '/Replicator/ReplicateInMongoDB',
                request_serializer=replicator__pb2.PostgresDBRequest.SerializeToString,
                response_deserializer=replicator__pb2.MongoDBReply.FromString,
                )


class ReplicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReplicateInMongoDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplicateInMongoDB': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateInMongoDB,
                    request_deserializer=replicator__pb2.PostgresDBRequest.FromString,
                    response_serializer=replicator__pb2.MongoDBReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Replicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Replicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReplicateInMongoDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Replicator/ReplicateInMongoDB',
            replicator__pb2.PostgresDBRequest.SerializeToString,
            replicator__pb2.MongoDBReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
